### ISSUE TITLE
Issues with Version Control section of docs

### ISSUE THREAD

**Issue by heraldofgargos** [AdamsLair/duality-docs#31] opened 2019-05-15 02:16 UTC
Hi there,

I've been following the [Duality and Version Control](https://docs.duality2d.net/pages/v3/Duality-and-Version-Control.html) section of the doc pages and noticed a couple of issues. 

In the section where it describes which files to ignore, the tutorial recommends ignoring `Duality.*` and `DualityPrimitives.*`. I've noticed that if these lib files are not pushed to the remote repository the DualityEditor application will not launch at all after cloning and it will not install any of the packages. 

The workaround was to re-add the Duality.dll and DualityPrimitives.dll lib files to the repository. Could the doc pages be amended to reflect this change?

Also, the link to the example gitignore file seems to 404.

**Comment by ilexp** [comment] 2019-05-15 16:31
Good call, this should be addressed. Putting it on my ToDo, but if anyone is interested in fixing this, feel free to grab.

**Comment by BobGneu** [comment] 2019-05-15 23:38
I can confirm that the `.gitignore` file is missing. 

This would be a pretty good opportunity to update it. 

@ilexp 
The following are the entries from the git repo from our old wiki: 

```gitignore
YourProjectFolder/Source/Packages/
YourProjectFolder/Backup/
YourProjectFolder/Temp/
YourProjectFolder/Plugins/*
!YourProjectFolder/Plugins/GamePlugin.core.dll
!YourProjectFolder/Plugins/GamePlugin.core.pdb
!YourProjectFolder/Plugins/GamePlugin.core.xml
!YourProjectFolder/Plugins/EditorPlugin.editor.dll
!YourProjectFolder/Plugins/EditorPlugin.editor.pdb
!YourProjectFolder/Plugins/EditorPlugin.editor.xml
YourProjectFolder/NVorbis.dll
YourProjectFolder/OpenTK.GLControl.dll
YourProjectFolder/OpenTK.GLControl.xml
YourProjectFolder/OpenTK.dll
YourProjectFolder/OpenTK.dll.config
YourProjectFolder/OpenTK.pdb
YourProjectFolder/OpenTK.xml
YourProjectFolder/FarseerDuality.xml
YourProjectFolder/FarseerDuality.pdb
YourProjectFolder/Microsoft.Web.XmlTransform.dll
YourProjectFolder/NVorbis.XML
YourProjectFolder/FarseerDuality.dll
YourProjectFolder/EditorUserData.xml
YourProjectFolder/PopupControl.dll
YourProjectFolder/PopupControl.pdb
YourProjectFolder/DualityUpdater.exe
YourProjectFolder/DualityPrimitives.pdb
YourProjectFolder/WeifenLuo.WinFormsUI.Docking.dll
YourProjectFolder/WeifenLuo.WinFormsUI.Docking.pdb
YourProjectFolder/logfile.txt
YourProjectFolder/logfile_editor.txt
YourProjectFolder/logfile_editor_prev.txt
YourProjectFolder/perflog.txt
YourProjectFolder/Aga.Controls.dll
YourProjectFolder/Aga.Controls.pdb
YourProjectFolder/Duality.pdb
YourProjectFolder/Duality.xml
YourProjectFolder/AdamsLair.WinForms.pdb
YourProjectFolder/AdamsLair.WinForms.xml
YourProjectFolder/perflog_editor.txt
YourProjectFolder/DDoc.chm
YourProjectFolder/DesignTimeData.dat
YourProjectFolder/DualityEditor.pdb
YourProjectFolder/DualityEditor.xml
YourProjectFolder/DualityLauncher.exe
YourProjectFolder/DualityLauncher.exe.config
YourProjectFolder/DualityLauncher.pdb
YourProjectFolder/DualityPrimitives.XML
YourProjectFolder/AdamsLair.WinForms.dll
YourProjectFolder/Source/Code/CorePlugin/bin/
YourProjectFolder/Source/Code/CorePlugin/obj/
YourProjectFolder/Source/Code/CorePlugin/GamePlugin.core.xml
YourProjectFolder/Source/Code/EditorPlugin/bin/
YourProjectFolder/Source/Code/EditorPlugin/obj/
YourProjectFolder/Source/Code/EditorPlugin/GamePlugin.core.xml
YourProjectFolder/Source/Code/ProjectPlugins.v12.suo
```

To address this ill put a PR together that will append the `.gitignore` listing above in stead of the message to download the link. 

As to the second point in the initial post, we ought to update the documentation, because the listing does not say we should ignore the dlls for `Duality` or `DualityPrimitives`, it does have the glob for all files saying they should be pulled down though. I'll get the PR together and we can discuss it there.

**Comment by BobGneu** [comment] 2019-05-15 23:46
One secondary note, we may want to also fold in the following to help lighten the repetitive nature of this document. It has some global rules to help cut down on the duplicated `bin/`, `obj/`, `log/` and otherwise files of a .net project and would likely be better off for a user that is first starting out. We may also want to go further, suggesting that users do not commit binary files (like their dlls) into the project at all. We do have the _Duality as a Self-Installing Application_  section suggesting this as a policy, but it is not present in the `.gitignore` listing

https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

**Comment by ilexp** [comment] 2019-05-20 19:01
> We may also want to go further, suggesting that users do not commit binary files (like their dlls) into the project at all.

This rule doesn't fully apply to Duality projects, as game resources (both imported and from the Source folder) have a place in the repository as well, and they're generally binary. Even the game plugin itself should be checked in, so non-programmers checking out the project are at least able to run the game and use the editor.

I mean, there are definitely design considerations on whether binary files and game resources should be in a git repo, whether to use LFS, a different version control system, or even two of them for different things - but I think those are more advanced topics that might be a bit too specific for a beginner who just wants to try version control.

> It has some global rules to help cut down on the duplicated bin/, obj/, log/ and otherwise files of a .net project and would likely be better off for a user that is first starting out.

Sounds good 👍 I wouldn't copy-paste the entire linked doc into ours though, as most of it is framework specific to frameworks that have only a slim chance of showing up in a Duality project. Maybe just go for the regular VS / msbuild stuff? If you want to grab this, I'm all for it.

**Comment by BobGneu** [comment] 2019-05-21 00:26
Gonna push another fix. 

https://docs.duality2d.net/pages/v2/Duality-and-Version-Control.html

the v2 formatting is pretty gross. 

Ill have it up this evening.

**Comment by BobGneu** [comment] 2019-05-21 00:40
@ilexp 

What do you think about the following as an addition? 

```
# User-specific files
*.rsuser
*.suo
*.user
*.userosscache
*.sln.docstates


# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/

# Visual Studio 2015/2017 cache/options directory
.vs/

# NuGet Packages
*.nupkg
# NuGet Symbol Packages
*.snupkg
# The packages folder can be ignored because of Package Restore
**/[Pp]ackages/*
# except build/, which is used as an MSBuild target.
!**/[Pp]ackages/build/
# NuGet v3's project.json files produces more ignorable files
*.nuget.props
*.nuget.targets

# Visual Studio cache files
# files ending in .cache can be ignored
*.[Cc]ache
# but keep track of directories ending in .cache
!?*.[Cc]ache/
```

**Comment by BobGneu** [comment] 2019-05-21 00:45
> This rule doesn't fully apply to Duality projects, as game resources (both imported and from the Source folder) have a place in the repository as well, and they're generally binary. Even the game plugin itself should be checked in, so non-programmers checking out the project are at least able to run the game and use the editor.
> 
> I mean, there are definitely design considerations on whether binary files and game resources should be in a git repo, whether to use LFS, a different version control system, or even two of them for different things - but I think those are more advanced topics that might be a bit too specific for a beginner who just wants to try version control.

I will defer to you on this note, but I also worry about the experience of novices running into merge conflicts within binary files in git, as that isn't great either.

**Comment by ilexp** [comment] 2019-05-25 11:58
> I will defer to you on this note, but I also worry about the experience of novices running into merge conflicts within binary files in git, as that isn't great either.

True, but I'm not sure this can be avoided entirely when it comes to content. Merge conflicts on actual content binaries like images or sounds just require human attention, and not having them in version control at all is not a great solution either. It's a deep topic that we only cover very shallowly.

I don't want to just block this though, we can still discuss it on a PR with the actual text you'd want to add or change - feel free to PR an extension to the version control article. Maybe we're talking about different things here anyway.

> What do you think about the following as an addition?

Looks good 👍 If you PR this as well, do a separate one from the above, so we can progress both at a different pace.

**Comment by BobGneu** [comment] 2019-05-26 18:38
Formatting changes are here: https://github.com/AdamsLair/duality-docs/pull/33/

I will get the updated block in later this evening.

**Comment by ilexp** [comment] 2019-07-28 12:35
> The workaround was to re-add the Duality.dll and DualityPrimitives.dll lib files to the repository. Could the doc pages be amended to reflect this change?

Fixed the docs section to no longer suggest adding them to git ignore.

Closing this, as all of the original points are now fixed. @BobGneu If you want to proceed with further improvements, feel free to PR later on.

**Closed as completed by ilexp** 2019-07-28 12:35 UTC
Labels: Improvement, Help Wanted, Good First Issue, Infrastructure
